// Code generated by Kitex v0.5.2. DO NOT EDIT.

package validator

import (
	psm "a/b/c/kitex_gen/psm"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Method1(ctx context.Context, Req *psm.IntValidate, callOptions ...callopt.Option) (r *psm.IntValidate, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kValidatorClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kValidatorClient struct {
	*kClient
}

func (p *kValidatorClient) Method1(ctx context.Context, Req *psm.IntValidate, callOptions ...callopt.Option) (r *psm.IntValidate, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Method1(ctx, Req)
}
